name: Check with Bandit

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  # Убедитесь, что указана актуальная версия

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit
        run: bandit -r . --exclude static/
