name: Check with Bandit

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lab3:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Bandit
        run: pip install bandit

      - name: Check security with Bandit
        run: bandit -r .
